# Generated by Django 5.2.8 on 2025-12-27 14:26

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='foto_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='foto_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='foto',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1', '16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=480, file_types=['AVIF'], grid_columns=12, height_field='foto_height', pixel_densities=[1, 2], upload_to='equipe/', verbose_name='Foto', width_field='foto_width'),
        ),
    ]
