# Generated by Django 5.2.8 on 2025-12-27 14:41

import core.models
import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipe_foto_height_equipe_foto_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='foto',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1', '16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=480, file_types=['AVIF'], grid_columns=12, height_field='foto_height', pixel_densities=[1, 2], upload_to=core.models.get_file_path, verbose_name='Foto', width_field='foto_width'),
        ),
    ]
