# Generated by Django 5.2.8 on 2025-12-31 12:04

import core.models
import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipe_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(choices=core.models.get_icon_name, max_length=20, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.AlterField(
            model_name='equipe',
            name='foto',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1', '16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 480}, container_width=480, file_types=['AVIF'], grid_columns=12, height_field='foto_height', pixel_densities=[1, 2], upload_to=core.models.get_file_path, verbose_name='Foto', width_field='foto_width'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=core.models.get_icon_name, max_length=20, verbose_name='Ícone'),
        ),
    ]
